/* Synthetic provider reports only. No AI/provider call, candidate audio or results. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({securityError_:(code,message)=>{const e=new Error(message);e.code=code;throw e;}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeakingAssessment.gs'),'utf8'),ctx);
let checks=0;const check=(n,v)=>{assert.ok(v,n);checks++;};
const recordings=[1,2,3].map(part=>({part,attemptID:'synthetic-attempt',receiptID:'synthetic-'+part,audioSHA256:String(part).repeat(64),decodedSeconds:part===2?120:240,decodingVerified:true}));
const valid={schemaVersion:1,status:'draft',audioEvaluated:true,provider:'synthetic-provider',modelVersion:'fixture-v1',attemptID:'synthetic-attempt',
recordings:recordings.map(({decodingVerified,attemptID,...r})=>r),criteria:Object.fromEntries(['fluencyCoherence','lexicalResource','grammar','pronunciation'].map(k=>[k,{band:6,feedback:'Synthetic evidence fixture',evidence:[1,2,3].map(part=>({part,source:'audio',startSeconds:0,endSeconds:1,observation:'Synthetic observation'}))}]))};
const inputSnapshot=JSON.stringify(valid);
const copy=x=>JSON.parse(JSON.stringify(x));
const validate=(report=valid,clips=recordings)=>{try{return ctx.validateMockSpeakingAssessment_(report,clips);}catch(e){return{code:e.code||e.message};}};
const reject=(n,change)=>{const r=copy(valid);change(r);check(n,validate(r).code==='ASSESSMENT_INVALID');};
check('complete synthetic report validated',validate().criteria.pronunciation.band===6);
check('validated report stays private draft for teacher review',validate().status==='draft'&&validate().teacherReviewRequired===true&&validate().releaseApproved===false&&!('overallBand' in validate()));
reject('transcript-only response rejected',r=>r.audioEvaluated=false);
reject('released provider status rejected',r=>r.status='released');
reject('missing provider version rejected',r=>r.modelVersion='');
reject('wrong attempt rejected',r=>r.attemptID='other');
reject('wrong receipt rejected',r=>r.recordings[0].receiptID='other');
reject('wrong byte fingerprint rejected',r=>r.recordings[0].audioSHA256='a'.repeat(64));
reject('changed decoded duration rejected',r=>r.recordings[0].decodedSeconds=239);
reject('missing part rejected',r=>r.recordings.pop());
reject('duplicate part rejected',r=>r.recordings[2]=r.recordings[0]);
reject('missing criterion rejected',r=>delete r.criteria.pronunciation);
reject('invented criterion rejected',r=>r.criteria.extra=r.criteria.grammar);
reject('out-of-range band rejected',r=>r.criteria.grammar.band=10);
reject('non-integer criterion band rejected',r=>r.criteria.grammar.band=6.5);
reject('text evidence rejected for pronunciation',r=>r.criteria.pronunciation.evidence[0].source='transcript');
reject('evidence beyond clip rejected',r=>r.criteria.pronunciation.evidence[0].endSeconds=999);
reject('negative evidence time rejected',r=>r.criteria.grammar.evidence[0].startSeconds=-1);
reject('zero length evidence rejected',r=>r.criteria.grammar.evidence[0].endSeconds=0);
reject('missing part evidence rejected',r=>r.criteria.grammar.evidence.pop());
reject('empty feedback rejected',r=>r.criteria.grammar.feedback=' ');
reject('unbounded observation rejected',r=>r.criteria.grammar.evidence[0].observation='x'.repeat(1001));
let bad=copy(recordings);bad[0].decodingVerified=false;check('unverified decoding rejected',validate(valid,bad).code==='ASSESSMENT_INVALID');
bad=copy(recordings);bad[2]=bad[0];check('duplicate verified identity rejected',validate(valid,bad).code==='ASSESSMENT_INVALID');
bad=copy(recordings);bad[0].audioSHA256='bad';check('malformed verified digest rejected',validate(valid,bad).code==='ASSESSMENT_INVALID');
check('no mutation of supplied synthetic report',JSON.stringify(valid)===inputSnapshot);
new vm.Script(fs.readFileSync(path.join(__dirname,'..','release-candidate','Code.gs'),'utf8'));
check('bundle contains exact assessment validator',fs.readFileSync(path.join(__dirname,'..','release-candidate','Code.gs'),'utf8').includes(fs.readFileSync(path.join(__dirname,'..','MockSpeakingAssessment.gs'),'utf8')));
console.log(JSON.stringify({speakingAssessmentContractChecks:checks,providerCalls:0,bandsReleased:0}));
