/* Synthetic private folder/files and authenticated sessions. No real audio or Drive access. */
const {createHarness}=require('./mock-entry.test.js'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const h=createHarness(),{ctx,req,sheets,clock}=h;let checks=0;const check=(n,v)=>{assert.ok(v,n);checks++;};
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockAttempts.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeaking.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeakingTimed.gs'),'utf8'),ctx);
ctx.initializeMockTests();ctx.initializeMockAttempts();ctx.initializeMockSpeaking();ctx.initializeMockSpeaking();

let enabled=false,shared=false,viewer=false,editor=false,group=false,paged=false,lookupError=false,files=[],createCount=0;
const original=ctx.PropertiesService.getScriptProperties;
ctx.PropertiesService.getScriptProperties=()=>({getProperty:k=>k==='DMI_MOCK_SPEAKING_ENABLED'?String(enabled):k==='DMI_MOCK_SPEAKING_FOLDER_ID'?'synthetic_folder_1234':original().getProperty(k)});
const user={getEmail:()=> 'owner@example.com'};
const privacy={getOwner:()=>user,getSharingAccess:()=>shared?'ANYONE':'PRIVATE',getViewers:()=>viewer?[user]:[],getEditors:()=>editor?[{getEmail:()=> 'other@example.com'}]:[]};
ctx.Session={getEffectiveUser:()=>user};
ctx.ScriptApp={getOAuthToken:()=> 'synthetic-test-token'};
ctx.UrlFetchApp={fetch:()=>({getResponseCode:()=>lookupError?403:200,getContentText:()=>JSON.stringify({permissions:[{type:'user',role:'owner',emailAddress:'owner@example.com'},...(group?[{type:'group',role:'reader',emailAddress:'synthetic@example.com'}]:[])],...(paged?{nextPageToken:'synthetic-next'}:{})})})};
const folder={...privacy,getId:()=> 'synthetic_folder_1234',getFilesByName:name=>{const matching=files.filter(f=>f.name===name);let i=0;return{hasNext:()=>i<matching.length,next:()=>matching[i++]};},
 createFile:blob=>{createCount++;const f={...privacy,name:blob.name,bytes:blob.bytes.slice(),getBlob(){return{getBytes:()=>this.bytes.slice()};},description:'',getId:()=> 'private-file-'+createCount,getDescription(){return this.description;},setDescription(d){this.description=d;}};files.push(f);return f;}};
ctx.DriveApp={Access:{PRIVATE:'PRIVATE'},getFolderById:()=>folder};
ctx.Utilities.base64Decode=s=>Array.from(Buffer.from(s,'base64'));
ctx.Utilities.newBlob=(bytes,mime,name)=>({bytes,mime,name});
const oldDigest=ctx.Utilities.computeDigest;ctx.Utilities.computeDigest=(algo,data)=>Array.isArray(data)?Array.from(crypto.createHash('sha256').update(Buffer.from(data)).digest()):oldDigest(algo,data);
const sitting=req('createMockSitting',h.payload()),id=sitting.sitting.id;
const attempt={AttemptID:'ATTEMPT-speaking',AdmissionID:'none',SittingID:id,StudentEmail:'one@example.com',StudentID:'S1',PaperID:'DMI-ACADEMIC-MOCK-01',PaperVersion:'v1',PaperDigest:'synthetic',StartedAt:new Date(clock.now-100000),ListeningDeadline:new Date(clock.now-3000),ReadingDeadline:new Date(clock.now-2000),WritingDeadline:new Date(clock.now-1000),StateJSON:JSON.stringify({sections:[0,1,2].map(()=>({closed:true,answers:{}}))}),Revision:0};
sheets.MockAttempts.appendRow(sheets.MockAttempts.vals[0].map(k=>attempt[k]));

ctx.Utilities.base64Encode=bytes=>Buffer.from(bytes).toString('base64');
const bytes=Buffer.alloc(128);bytes.set([26,69,223,163]);enabled=true;
const uploaded=req('uploadMockSpeaking',{sittingID:id,part:1,requestID:crypto.randomUUID(),mime:'audio/webm',durationSeconds:30,audioBase64:bytes.toString('base64')},'student');
check('synthetic recording acknowledged',uploaded.ok&&createCount===1);
const p={attemptID:attempt.AttemptID,part:1,receiptID:uploaded.receipt.id};

vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeakingRetention.gs'),'utf8'),ctx);
ctx.Session.getActiveUser=()=>user;
const preview=days=>{try{return ctx.previewMockSpeakingRetention(days);}catch(e){return{code:e.code||e.message};}};
const header=sheets.MockSpeakingUploads.vals[0],row=sheets.MockSpeakingUploads.vals[1];
const col=k=>header.indexOf(k),set=(k,v)=>row[col(k)]=v;
const originalRow=row.slice(),originalMarks=JSON.stringify(sheets.Marks.vals),originalResults=JSON.stringify(sheets.ExamResults.vals);
ctx.Session.getActiveUser=()=>({getEmail:()=> 'teacher@example.com'});
check('non-owner fails closed',preview(30).code==='FORBIDDEN');
ctx.Session.getActiveUser=()=>({getEmail:()=> ''});
check('unknown active user fails closed',preview(30).code==='FORBIDDEN');
ctx.Session.getActiveUser=()=>user;
for(const v of [undefined,'30',0,6,366,30.5,NaN,Infinity])check('explicit bounded numeric policy required '+v,preview(v).code==='VALIDATION');
check('recent recording not proposed',preview(30).candidates.length===0);
set('UploadedAt',new Date(clock.now-30*86400000));
let result=preview(30);
check('cutoff inclusive',result.candidates.length===1);
check('preview always dry run and unapproved',result.dryRun===true&&result.deletionEnabled===false&&result.candidates[0].deletionApproved===false);
check('unreviewed recording explicitly held for assessment',result.candidates[0].holdForAssessment===true);
check('no raw audio or file IDs returned',!JSON.stringify(result).includes('audioBase64')&&!JSON.stringify(result).includes('private-file'));
files[0].getBlob=()=>{throw new Error('Preview must not read audio');};
check('preview never reads audio bytes',preview(30).ok===true);
set('UploadedAt','invalid');
check('invalid date held',preview(30).held[0].reason==='INVALID_METADATA');
set('UploadedAt',new Date(clock.now+1));
check('future date held',preview(30).held[0].reason==='INVALID_METADATA');
set('UploadedAt',new Date(clock.now-31*86400000));
sheets.MockSpeakingUploads.vals.push(row.slice());
check('duplicate identities held not proposed',preview(30).candidates.length===0&&preview(30).held.length===2);
sheets.MockSpeakingUploads.vals.pop();
const oldID=row[col('FileID')];set('FileID','wrong');
check('file identity mismatch held',preview(30).held[0].reason==='FILE_IDENTITY_CONFLICT');set('FileID',oldID);
const oldName=files[0].name;files[0].name='unavailable';
check('missing file held',preview(30).held[0].reason==='FILE_UNAVAILABLE');files[0].name=oldName;
group=true;check('shared permissions fail entire preview closed',preview(30).code==='MOCK_NOT_READY');group=false;
lookupError=true;check('permission lookup failure fails closed',preview(30).code==='MOCK_NOT_READY');lookupError=false;
sheets.MockSpeakingReviews.appendRow(sheets.MockSpeakingReviews.vals[0].map(k=>({AttemptID:attempt.AttemptID,Part:1,ReceiptID:uploaded.receipt.id,Feedback:'Synthetic review'})[k]||''));
check('matching review counted',preview(30).candidates[0].reviewCount===1&&preview(30).candidates[0].holdForAssessment===false);
check('no file deletion or receipt mutation',createCount===1&&files.length===1&&sheets.MockSpeakingUploads.vals.length===2);
check('scores untouched',JSON.stringify(sheets.Marks.vals)===originalMarks&&JSON.stringify(sheets.ExamResults.vals)===originalResults);
console.log(JSON.stringify({speakingRetentionChecks:checks,realAudioReads:0,deletions:0,policyConfigured:false}));
