/* Synthetic private folder/files and authenticated sessions. No real audio or Drive access. */
const {createHarness}=require('./mock-entry.test.js'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const h=createHarness(),{ctx,req,sheets,clock}=h;let checks=0;const check=(n,v)=>{assert.ok(v,n);checks++;};
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockAttempts.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeaking.gs'),'utf8'),ctx);
ctx.initializeMockTests();ctx.initializeMockAttempts();ctx.initializeMockSpeaking();ctx.initializeMockSpeaking();
check('Speaking setup additive and idempotent',sheets.MockSpeakingUploads.vals.length===1&&sheets.Marks.vals.length===1);
let enabled=false,shared=false,viewer=false,editor=false,files=[],createCount=0;
const original=ctx.PropertiesService.getScriptProperties;
ctx.PropertiesService.getScriptProperties=()=>({getProperty:k=>k==='DMI_MOCK_SPEAKING_ENABLED'?String(enabled):k==='DMI_MOCK_SPEAKING_FOLDER_ID'?'synthetic_folder_1234':original().getProperty(k)});
const user={getEmail:()=> 'owner@example.com'};
const privacy={getOwner:()=>user,getSharingAccess:()=>shared?'ANYONE':'PRIVATE',getViewers:()=>viewer?[user]:[],getEditors:()=>editor?[{getEmail:()=> 'other@example.com'}]:[]};
ctx.Session={getEffectiveUser:()=>user};
const folder={...privacy,getFilesByName:name=>{const matching=files.filter(f=>f.name===name);let i=0;return{hasNext:()=>i<matching.length,next:()=>matching[i++]};},
 createFile:blob=>{createCount++;const f={...privacy,name:blob.name,description:'',getId:()=> 'private-file-'+createCount,getDescription(){return this.description;},setDescription(d){this.description=d;}};files.push(f);return f;}};
ctx.DriveApp={Access:{PRIVATE:'PRIVATE'},getFolderById:()=>folder};
ctx.Utilities.base64Decode=s=>Array.from(Buffer.from(s,'base64'));
ctx.Utilities.newBlob=(bytes,mime,name)=>({bytes,mime,name});
const oldDigest=ctx.Utilities.computeDigest;ctx.Utilities.computeDigest=(algo,data)=>Array.isArray(data)?Array.from(crypto.createHash('sha256').update(Buffer.from(data)).digest()):oldDigest(algo,data);
const sitting=req('createMockSitting',h.payload()),id=sitting.sitting.id;
const attempt={AttemptID:'ATTEMPT-speaking',AdmissionID:'none',SittingID:id,StudentEmail:'one@example.com',StudentID:'S1',PaperID:'DMI-ACADEMIC-MOCK-01',PaperVersion:'v1',PaperDigest:'synthetic',StartedAt:new Date(clock.now-100000),ListeningDeadline:new Date(clock.now-3000),ReadingDeadline:new Date(clock.now-2000),WritingDeadline:new Date(clock.now-1000),StateJSON:JSON.stringify({sections:[0,1,2].map(()=>({closed:true,answers:{}}))}),Revision:0};
sheets.MockAttempts.appendRow(sheets.MockAttempts.vals[0].map(k=>attempt[k]));
const bytes=Buffer.alloc(128);bytes.set([26,69,223,163]);const p={sittingID:id,part:1,requestID:crypto.randomUUID(),mime:'audio/webm',durationSeconds:30,audioBase64:bytes.toString('base64')};
check('disabled capture fails closed',req('uploadMockSpeaking',p,'student').code==='MOCK_NOT_READY'&&createCount===0);
enabled=true;
check('anonymous cannot upload',req('uploadMockSpeaking',{...p,sessionToken:''},'student').code==='UNAUTHENTICATED');
check('teacher cannot submit student recording',req('uploadMockSpeaking',p).code==='FORBIDDEN');
check('other student cannot upload for candidate',req('uploadMockSpeaking',{...p,attemptID:attempt.AttemptID},'second').code==='MOCK_NOT_STARTED');
shared=true;check('public folder rejected before write',req('uploadMockSpeaking',p,'student').code==='MOCK_NOT_READY'&&createCount===0);shared=false;
viewer=true;check('explicit viewer rejected before write',req('uploadMockSpeaking',p,'student').code==='MOCK_NOT_READY');viewer=false;
editor=true;check('explicit editor rejected before write',req('uploadMockSpeaking',p,'student').code==='MOCK_NOT_READY');editor=false;
for(const bad of [{part:4},{durationSeconds:0},{durationSeconds:361},{mime:'text/html'},{audioBase64:'invalid!'},{audioBase64:Buffer.alloc(128).toString('base64')},{mime:'audio/ogg'}])
 check('invalid upload rejected',req('uploadMockSpeaking',{...p,...bad},'student').code==='VALIDATION');
check('Speaking uploads require original part order',req('uploadMockSpeaking',{...p,part:3},'student').code==='MOCK_SECTION_ORDER'&&createCount===0);
const first=req('uploadMockSpeaking',p,'student');check('private recording gets pending receipt',first.ok&&first.receipt.part===1&&first.receipt.bytes===128&&first.assessment==='pending'&&createCount===1);
check('receipt hides file id and audio',!JSON.stringify(first).includes('private-file')&&!JSON.stringify(first).includes(p.audioBase64));
check('lost response exact retry creates no duplicate',req('uploadMockSpeaking',p,'student').recovered&&createCount===1&&sheets.MockSpeakingUploads.vals.length===2);
check('changed retry refused',req('uploadMockSpeaking',{...p,durationSeconds:31},'student').code==='VALIDATION');
check('second recording cannot overwrite acknowledged part',req('uploadMockSpeaking',{...p,requestID:crypto.randomUUID()},'student').code==='MOCK_RECORDING_EXISTS');
const append=sheets.MockSpeakingUploads.appendRow;let fail=true;sheets.MockSpeakingUploads.appendRow=row=>{if(fail){fail=false;throw Error('Synthetic interrupted metadata save');}return append(row);};
const second={...p,part:2,requestID:crypto.randomUUID(),durationSeconds:60};check('file survives interrupted metadata write',!req('uploadMockSpeaking',second,'student').ok&&createCount===2);
check('orphan recovered without duplicate file',req('uploadMockSpeaking',second,'student').ok&&createCount===2&&sheets.MockSpeakingUploads.vals.length===3);
check('candidate restores acknowledged receipts',req('myMockSpeakingUploads',{sittingID:id},'student').receipts.length===2);
check('student denied teacher listing',req('listMockSpeakingUploads',{attemptID:attempt.AttemptID},'student').code==='FORBIDDEN');
check('teacher sees pending metadata only',req('listMockSpeakingUploads',{attemptID:attempt.AttemptID}).receipts.length===2);
sheets.MockAttempts.vals[1][sheets.MockAttempts.vals[0].indexOf('WritingDeadline')]=new Date(clock.now+1000);
check('written deadline cannot be bypassed by early submit',req('myMockSpeakingUploads',{sittingID:id},'student').code==='MOCK_SPEAKING_NOT_READY');
check('existing scores stay untouched',sheets.Marks.vals.length===1&&sheets.ExamResults.vals.length===1);
new vm.Script(fs.readFileSync(path.join(__dirname,'..','release-candidate','Code.gs'),'utf8'));
check('consolidated module matches',fs.readFileSync(path.join(__dirname,'..','release-candidate','Code.gs'),'utf8').includes(fs.readFileSync(path.join(__dirname,'..','MockSpeaking.gs'),'utf8')));
console.log(JSON.stringify({speakingUploadChecks:checks,realDriveWrites:0,provider:'NOT_CONFIGURED',speakingEnabled:false}));
