/* Synthetic teacher review workbook; no network or real candidates. */
const {chromium}=require('playwright'),{createHarness}=require('./mock-entry.test.js'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),h=createHarness();vm.runInContext(fs.readFileSync(path.join(root,'MockAttempts.gs'),'utf8'),h.ctx);h.ctx.initializeMockTests();h.ctx.initializeMockAttempts();
const created=h.req('createMockSitting',h.payload()),id=created.sitting.id;
const paper={listeningSeconds:1800,sections:['listening','reading','writing'].map((name,i)=>({name,questions:Array.from({length:i===2?2:40},(_,j)=>({id:String(j+1),prompt:'Synthetic '+name+' '+(j+1)}))}))};
const json=JSON.stringify(paper);h.sheets.MockPapers.appendRow(['DMI-ACADEMIC-MOCK-01','v1',true,true,json]);
const fields={AttemptID:'ATTEMPT-synthetic',AdmissionID:'none',SittingID:id,StudentEmail:'one@example.com',StudentID:'S1',PaperID:'DMI-ACADEMIC-MOCK-01',PaperVersion:'v1',PaperDigest:h.ctx.digest_(json),StartedAt:new Date(h.clock.now-100000),ListeningDeadline:new Date(h.clock.now-3000),ReadingDeadline:new Date(h.clock.now-2000),WritingDeadline:new Date(h.clock.now-1000),StateJSON:JSON.stringify({sections:[{answers:{'1':'A'},closed:true},{answers:{'1':'B'},closed:true},{answers:{'1':'<img src=x onerror=alert(1)>','2':'Synthetic essay'},closed:true}]}),Revision:0};
h.sheets.MockAttempts.appendRow(h.sheets.MockAttempts.vals[0].map(k=>fields[k]));
let checks=0,lose=true;const check=(n,v)=>{assert.ok(v,n);checks++;};
(async()=>{const browser=await chromium.launch(),context=await browser.newContext(),page=await context.newPage();
await page.exposeFunction('reviewCall',async(a,p)=>{const r=h.req(a,p);if(a==='saveMockWritingReview'&&lose){lose=false;throw Error('Simulated lost response');}return r;});
await context.route('**/*',async route=>{const rel=new URL(route.request().url()).pathname.split('/').pop();
if(rel==='dmi-auth.js')return route.fulfill({contentType:'text/javascript',body:"window.DMI_AUTH={requireRole:async()=>({role:'teacher',user:{name:'Teacher'}}),call:(a,p)=>window.reviewCall(a,p)};"});
const f=path.join(root,rel);if(fs.existsSync(f))return route.fulfill({contentType:rel.endsWith('.js')?'text/javascript':rel.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(f)});return route.abort();});
await page.goto('https://draft.example/mock-review.html');await page.locator('#sitting option').waitFor();
await page.locator('#load').click();await page.locator('#attempt option').waitFor();await page.locator('#open').click();await page.locator('#review').waitFor({state:'visible'});
check('saved essay visible',(await page.locator('#answers').textContent()).includes('Synthetic essay'));
check('answers cannot inject HTML',await page.locator('#answers img').count()===0);
check('unreviewed band stays blank',await page.locator('#score-task').inputValue()==='');
for(const k of ['task','coherence','lexical','grammar'])await page.locator('#score-'+k).fill('6');
await page.locator('#feedback').fill('Synthetic feedback');await page.locator('#save').click();await page.locator('#retry').waitFor({state:'visible'});
check('uncertain save freezes rubric',await page.locator('#feedback').isDisabled());
await page.locator('#retry').click();await page.getByText('Teacher review saved. Results remain unreleased.',{exact:true}).waitFor();
check('lost response retry has one history row',h.sheets.MockReviews.vals.length===2);
check('saved rubric shown',await page.locator('#score-task').inputValue()==='6');
check('saved feedback shown',await page.locator('#feedback').inputValue()==='Synthetic feedback');
await page.locator('#task').selectOption('2');check('unmarked Task 2 stays blank',await page.locator('#score-task').inputValue()==='');
check('marks remain untouched',h.sheets.Marks.vals.length===1&&h.sheets.ExamResults.vals.length===1);
await page.setViewportSize({width:390,height:844});check('mobile fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const out=path.join(root,'artifacts');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'mock-review-synthetic.png'),fullPage:true});
await context.close();await browser.close();console.log(JSON.stringify({teacherReviewBrowserChecks:checks,liveWorkbookWrites:0}));})().catch(e=>{console.error(e);process.exit(1);});
