/* Synthetic private folder/files and authenticated sessions. No real audio or Drive access. */
const {createHarness}=require('./mock-entry.test.js'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const h=createHarness(),{ctx,req,sheets,clock}=h;let checks=0;const check=(n,v)=>{assert.ok(v,n);checks++;};
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockAttempts.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeaking.gs'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','MockSpeakingTimed.gs'),'utf8'),ctx);
ctx.initializeMockTests();ctx.initializeMockAttempts();ctx.initializeMockSpeaking();ctx.initializeMockSpeaking();
check('Speaking setup additive and idempotent',sheets.MockSpeakingUploads.vals.length===1&&sheets.Marks.vals.length===1);
let timedEnabled=false,enabled=false,shared=false,viewer=false,editor=false,group=false,paged=false,lookupError=false,files=[],createCount=0;
const original=ctx.PropertiesService.getScriptProperties;
ctx.PropertiesService.getScriptProperties=()=>({getProperty:k=>k==='DMI_MOCK_SPEAKING_TIMED_ENABLED'?String(timedEnabled):k==='DMI_MOCK_SPEAKING_ENABLED'?String(enabled):k==='DMI_MOCK_SPEAKING_FOLDER_ID'?'synthetic_folder_1234':original().getProperty(k)});
const user={getEmail:()=> 'owner@example.com'};
const privacy={getOwner:()=>user,getSharingAccess:()=>shared?'ANYONE':'PRIVATE',getViewers:()=>viewer?[user]:[],getEditors:()=>editor?[{getEmail:()=> 'other@example.com'}]:[]};
ctx.Session={getEffectiveUser:()=>user};
ctx.ScriptApp={getOAuthToken:()=> 'synthetic-test-token'};
ctx.UrlFetchApp={fetch:()=>({getResponseCode:()=>lookupError?403:200,getContentText:()=>JSON.stringify({permissions:[{type:'user',role:'owner',emailAddress:'owner@example.com'},...(group?[{type:'group',role:'reader',emailAddress:'synthetic@example.com'}]:[])],...(paged?{nextPageToken:'synthetic-next'}:{})})})};
const folder={...privacy,getId:()=> 'synthetic_folder_1234',getFilesByName:name=>{const matching=files.filter(f=>f.name===name);let i=0;return{hasNext:()=>i<matching.length,next:()=>matching[i++]};},
 createFile:blob=>{createCount++;const f={...privacy,name:blob.name,description:'',getId:()=> 'private-file-'+createCount,getDescription(){return this.description;},setDescription(d){this.description=d;}};files.push(f);return f;}};
ctx.DriveApp={Access:{PRIVATE:'PRIVATE'},getFolderById:()=>folder};
ctx.Utilities.base64Decode=s=>Array.from(Buffer.from(s,'base64'));
ctx.Utilities.newBlob=(bytes,mime,name)=>({bytes,mime,name});
const oldDigest=ctx.Utilities.computeDigest;ctx.Utilities.computeDigest=(algo,data)=>Array.isArray(data)?Array.from(crypto.createHash('sha256').update(Buffer.from(data)).digest()):oldDigest(algo,data);
const sitting=req('createMockSitting',h.payload()),id=sitting.sitting.id;
const attempt={AttemptID:'ATTEMPT-speaking',AdmissionID:'none',SittingID:id,StudentEmail:'one@example.com',StudentID:'S1',PaperID:'DMI-ACADEMIC-MOCK-01',PaperVersion:'v1',PaperDigest:'synthetic',StartedAt:new Date(clock.now-100000),ListeningDeadline:new Date(clock.now-3000),ReadingDeadline:new Date(clock.now-2000),WritingDeadline:new Date(clock.now-1000),StateJSON:JSON.stringify({sections:[0,1,2].map(()=>({closed:true,answers:{}}))}),Revision:0};
sheets.MockAttempts.appendRow(sheets.MockAttempts.vals[0].map(k=>attempt[k]));
enabled=true;
const timedReq=req;
const originalPaper=ctx.mockPaper_;
let speakingFixture={speakingTiming:{reviewed:true,part1:Array.from({length:8},(_,i)=>({prompt:'Synthetic introduction '+i,seconds:30})),cue:'Synthetic private cue',part3:Array.from({length:4},(_,i)=>({prompt:'Synthetic discussion '+i,seconds:60}))}};
ctx.mockPaper_=()=>({paper:speakingFixture,digest:'synthetic'});
const timedP={sittingID:id,consent:true,microphoneReady:true};
check('timed gate disabled',timedReq('startMockSpeakingTimed',timedP,'student').code==='MOCK_NOT_READY');
timedEnabled=true;
for(const action of ['startMockSpeakingTimed','resumeMockSpeakingTimed']){
 check('timed GET rejected: '+action,req(action,timedP,'student',false).code==='POST_REQUIRED');
 check('other attempt denied: '+action,req(action,{...timedP,attemptID:'ATTEMPT-other'},'student').code==='FORBIDDEN');
}
check('timed teacher denied',timedReq('startMockSpeakingTimed',timedP).code==='FORBIDDEN');
check('timed other candidate denied',timedReq('startMockSpeakingTimed',timedP,'second').code==='MOCK_NOT_STARTED');
check('timed anonymous denied',timedReq('startMockSpeakingTimed',{...timedP,sessionToken:''},'student').code==='UNAUTHENTICATED');
check('resume cannot create clock',timedReq('resumeMockSpeakingTimed',timedP,'student').code==='MOCK_SPEAKING_NOT_STARTED');
check('consent needed before start',timedReq('startMockSpeakingTimed',{...timedP,consent:false},'student').code==='VALIDATION');
check('preflight needed before start',timedReq('startMockSpeakingTimed',{...timedP,microphoneReady:false},'student').code==='VALIDATION');
speakingFixture.speakingTiming.reviewed=false;
check('unreviewed Speaking fails closed',timedReq('startMockSpeakingTimed',timedP,'student').code==='MOCK_NOT_READY');speakingFixture.speakingTiming.reviewed=true;
speakingFixture.speakingTiming.part1[0].seconds=14;
check('invalid prompt duration rejected',timedReq('startMockSpeakingTimed',timedP,'student').code==='MOCK_NOT_READY');speakingFixture.speakingTiming.part1[0].seconds=30;
speakingFixture.speakingTiming.part3[0].seconds=30;
check('part shorter than four minutes rejected',timedReq('startMockSpeakingTimed',timedP,'student').code==='MOCK_NOT_READY');speakingFixture.speakingTiming.part3[0].seconds=60;
check('text false consent is rejected',timedReq('startMockSpeakingTimed',{...timedP,consent:'false'},'student').code==='VALIDATION');
check('text false preflight is rejected',timedReq('startMockSpeakingTimed',{...timedP,microphoneReady:'false'},'student').code==='VALIDATION');
check('truthy numeric flag is rejected',timedReq('startMockSpeakingTimed',{...timedP,consent:1},'student').code==='VALIDATION');
const timedAudio=Buffer.alloc(128);timedAudio.set([26,69,223,163]);
const upload=(part,recordingID,duration=30)=>({sittingID:id,part,recordingID,durationSeconds:duration,mime:'audio/webm',audioBase64:timedAudio.toString('base64'),requestID:crypto.randomUUID()});
const timedStart=timedReq('startMockSpeakingTimed',{...timedP,consent:'true',microphoneReady:'true'},'student'),started=clock.now;
check('clock begins at Part 1 for eleven minutes',timedStart.ok&&timedStart.speaking.stage.phase==='part1'&&timedStart.speaking.totalSeconds===660);
check('future private prompts not exposed',!JSON.stringify(timedStart).includes('Synthetic private cue')&&!JSON.stringify(timedStart).includes('Synthetic discussion'));
const part1Upload=upload(1,timedStart.speaking.recordingWindow.recordingID);
check('current part recording identity supplied',typeof part1Upload.recordingID==='string');
check('premature timed upload refused',req('uploadMockSpeaking',part1Upload,'student').code==='MOCK_UPLOAD_WINDOW'&&createCount===0);
clock.now=started+31000;
const resumed=timedReq('resumeMockSpeakingTimed',{...timedP,startedAt:'2099-01-01',elapsed:0},'student');
check('server advances question ignoring client clock',resumed.ok&&resumed.speaking.stage.prompt==='Synthetic introduction 1');
check('late join gets no new recording identity',resumed.speaking.recordingWindow.recordingID===null&&!resumed.speaking.recordingWindow.eligible);
check('start retry does not restart timer',timedReq('startMockSpeakingTimed',timedP,'student').speaking.startedAt===timedStart.speaking.startedAt);
clock.now=started+240000;
const prep=timedReq('resumeMockSpeakingTimed',timedP,'student');
check('Part 2 has one minute preparation',prep.speaking.stage.phase==='preparation'&&new Date(prep.speaking.stage.deadline)-clock.now===60000);
check('preparation creates no recording window',prep.speaking.recordingWindow===null);
check('wrong recording identity rejected',req('uploadMockSpeaking',{...part1Upload,recordingID:'other'},'student').code==='MOCK_RECORDING_ID'&&createCount===0);
check('completed Part 1 upload accepted',req('uploadMockSpeaking',part1Upload,'student').ok&&createCount===1);
check('lost acknowledgement exact retry recovered',req('uploadMockSpeaking',part1Upload,'student').recovered&&createCount===1);
check('retry identity cannot change recording ticket',req('uploadMockSpeaking',{...part1Upload,recordingID:'changed'},'student').code==='VALIDATION');
clock.now=started+300000;
const talk=timedReq('resumeMockSpeakingTimed',timedP,'student');
check('Part 2 long turn limited to two minutes',talk.speaking.stage.phase==='long_turn'&&new Date(talk.speaking.stage.deadline)-clock.now===120000);
const part2Upload=upload(2,talk.speaking.recordingWindow.recordingID,120);
check('Part 2 recording begins after preparation',talk.speaking.recordingWindow.part===2&&talk.speaking.recordingWindow.eligible);
clock.now=started+420000;
check('Part 3 starts after long turn',timedReq('resumeMockSpeakingTimed',timedP,'student').speaking.stage.phase==='part3');
const part3Start=timedReq('resumeMockSpeakingTimed',timedP,'student'),part3Upload=upload(3,part3Start.speaking.recordingWindow.recordingID,240);
const append=sheets.MockSpeakingUploads.appendRow;let interrupt=true;sheets.MockSpeakingUploads.appendRow=r=>{if(interrupt){interrupt=false;throw Error('Synthetic metadata interruption');}return append(r);};
check('timed orphan left after metadata failure',!req('uploadMockSpeaking',part2Upload,'student').ok&&createCount===2);
clock.now=started+1321000;
check('existing exact orphan recovers beyond upload grace',req('uploadMockSpeaking',part2Upload,'student').ok&&createCount===2);
clock.now=started+1561000;
check('new late part upload refused',req('uploadMockSpeaking',part3Upload,'student').code==='MOCK_UPLOAD_WINDOW'&&createCount===2);
check('acknowledged retry recovers beyond grace',req('uploadMockSpeaking',part1Upload,'student').recovered&&createCount===2);
clock.now=started+660000;
check('exact deadline removes prompt',timedReq('resumeMockSpeakingTimed',timedP,'student').speaking.stage===null);
check('finished test cannot restart',timedReq('startMockSpeakingTimed',timedP,'student').speaking.status==='finished');
ctx.mockPaper_=()=>({paper:speakingFixture,digest:'changed'});
check('paper alteration blocks resume',timedReq('resumeMockSpeakingTimed',timedP,'student').code==='MOCK_PAPER_CHANGED');
ctx.mockPaper_=originalPaper;


check('scores unchanged',sheets.Marks.vals.length===1&&sheets.ExamResults.vals.length===1);
const bundle=fs.readFileSync(path.join(__dirname,'..','release-candidate','Code.gs'),'utf8');
new vm.Script(bundle);
check('deployment bundle includes exact timing module',bundle.includes(fs.readFileSync(path.join(__dirname,'..','MockSpeakingTimed.gs'),'utf8')));
console.log(JSON.stringify({speakingTimedBackendChecks:checks,dispatch:'VERIFIED_POST_HANDLER',liveWrites:0}));
